// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/6 13:49:48
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/兴元/开门柜项目/chess/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/兴元/开门柜项目/chess/blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/兴元/开门柜项目/chess/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/兴元/开门柜项目/chess/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/兴元/开门柜项目/chess/blog/plugins/**/*.{js,ts,mjs}","E:/兴元/开门柜项目/chess/blog/composables/**/*.{js,ts,mjs}","E:/兴元/开门柜项目/chess/blog/utils/**/*.{js,ts,mjs}","E:/兴元/开门柜项目/chess/blog/pages/articles.vue","E:/兴元/开门柜项目/chess/blog/pages/create-article.vue","E:/兴元/开门柜项目/chess/blog/pages/index.vue","E:/兴元/开门柜项目/chess/blog/pages/info.vue","E:/兴元/开门柜项目/chess/blog/pages/login.vue","E:/兴元/开门柜项目/chess/blog/pages/projects.vue","E:/兴元/开门柜项目/chess/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/兴元/开门柜项目/chess/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/兴元/开门柜项目/chess/blog/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;